model_id: "CompVis/stable-diffusion-v1-4"
url: 'http://images.cocodataset.org/val2017/000000039769.jpg'
prompt_text: "a photography of"
max_length: 75
return_tensors: "pt"
output_path: "../MLops_project_Group18/reports/figures/test1.png"
pretrained_model: "Salesforce/blip-image-captioning-large"
min_length: 40
num_beams: 5